export const KEYWORDS = ['mai táng trọn gói',
    'dịch vụ mai táng',
    'dịch vụ tang lễ',
    'tổ chức tang lễ',
    'mai táng tại nhà',
    'mai táng tại bệnh viện',
    'dịch vụ hỏa táng',
    'dịch vụ an táng',
    'dịch vụ mai táng trọn gói giá rẻ',
    'dịch vụ mai táng uy tín',
    'dịch vụ hậu sự',
    'dịch vụ tang lễ trọn gói giá rẻ',
    'dịch vụ mai táng trọn gói uy tín',
    'dịch vụ mai táng trọn gói tại TPHCM',
]